apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config/config.yaml
  - config/secret.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - redis/service.yaml
  - redis/deployment.yaml
  - backend/service.yaml
  - backend/deployment.yaml
  - backend/hpa.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml
  - ingress/ingress.yaml
